version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  # disable dynVer
  - ps: Remove-Item Env:\CI
  - cmd: sbt version & exit 0

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  JAVA_OPTS: -Xss2m -Xmx1024m -XX:-TieredCompilation -XX:ReservedCodeCacheSize=48m -Dfile.encoding=UTF-8 -Djna.nosys=true
  matrix:
    - CI_TEST: ci-212

build_script:
  - sbt compile
  
test_script:
  - sbt ci-212-windows

# see CONTRIBUTING.md#AppVeyor
cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'
  - '%LOCALAPPDATA%\Coursier\cache'
  - '%USERPROFILE%\scoop\cache'
